config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end
  get 'users/:user_id/posts_list', to: 'api#list_posts', as: :list_posts
  get 'users/:user_id/posts/:post_id/comments_list', to: 'api#list_comments', as: :list_comments
  post 'users/:user_id/posts/:post_id/comment_create', to: 'api#create_comment', as: :create_comment
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments, foreign_key: :post_id, dependent: :delete_all
  has_many :likes, foreign_key: :post_id, dependent: :delete_all

  after_save :update_posts_counter

  validates :title, presence: true, length: { in: 4..250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def last_five_comments
    comments.includes(:post).order(created_at: :desc).limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.includes(:author, :comments).where(author: params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @user = current_user
    @post = @user.posts.new
  end

  def create
    @user = current_user
    @post = @user.posts.create(post_params)
    if @post.save
      flash[:notice] = 'New post created successfully.'
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:alert] = 'Post creation failed'
      render action: 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.author), notice: "Successfully deleted the post #{@post.title}."
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/shared/post/_comment.html.erb
<div class="comments">
  <% comments.each do |comment| %>
    <div class="d-flex justify-content-between align-items-center">
      <p><%= comment.author.name %> : <%= comment.text %></p>
      <% if can? :delete, comment %>
        <%= button_to "Delete", user_post_comment_path(comment.author, comment.post, comment),
                      method: :delete, class: "btn btn-outline-danger btn-sm" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/post/_post_summary.html.erb
<div class="post_sum">
  <h4><%= link_to post.title, user_post_path(post.author, post) %></h4>
  <p class="text"><%= post.text %></p>
  <div class="interactions">
    <p>Comments: <span><%= post.comments.count %></span></p>
    <p>Likes: <span><%= post.likes.count %></span></p>
  </div>
</div>