config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:index, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end
  get 'users/:user_id/posts_list', to: 'api#list_posts', as: :list_posts
  get 'users/:user_id/posts/:post_id/comments_list', to: 'api#list_comments', as: :list_comments
  post 'users/:user_id/posts/:post_id/comment_create', to: 'api#create_comment', as: :create_comment
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable, :confirmable

  has_many :comments, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  def admin?
    role == 'admin'
  end

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :add_token

  def add_token
    update_column(:authentication_token, ApiHelper::JsonWebToken.encode(email))
  end

  def last_three_posts
    posts.includes(:author).order(created_at: :desc).limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<% if @users.count > 0 %>
  <% @users.each do |user| %>
    <%= render partial: "shared/user/user_header", locals: { user: user } %>
  <% end %>
<% else %>
  <p>No users found</p>
<% end %>

app/views/users/show.html.erb
<%= render partial: "shared/user/user_header", locals: { user: @user } %>
<div class="bio">
  <h4>Bio</h4>
  <p><%= @user.bio %></p>
</div>
<% if @user.posts.count > 0 %>
  <% @user.last_three_posts.each do |post| %>
    <%= render partial: "shared/post/post_summary", locals: { post: post } %>
  <% end %>
  <%= link_to "See all posts", user_posts_path(@user), class: 'all_posts' %>
<% else %>
  <p>This user has no post</p>
<% end %>
<% if current_user == @user %>
  <%= link_to "Create new post", new_user_post_path(@user), class: "all_posts" %>
<% end %>